image: docker:latest
services:
  - docker:18.09.6-dind

stages:
  - build
  - package
  - deploy
  - analysis

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"
  REPOSITORY_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_IID}"
  REPOSITORY_IMAGE_NGINX: "${CI_REGISTRY}/${CI_PROJECT_PATH}:nginx-${CI_PIPELINE_IID}"
  CONFIG_FILE: "project_50/configs/kuber_config.py"
  CONFIG_FILE_EXAMPLE: "project_50/configs/example_config.py.txt"

APP_Image_Package:
  tags:
    - kuber
  stage: package
  only:
    - master
  image: docker:18.09.6-dind
  script:
    # sed works as replace WHAT WITH WHERE
    - sed -i -e "s@__SECRET_KEY__@${SECRET_KEY}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__ALLOWED_HOSTS__@${ALLOWED_HOSTS}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__DB_HOST__@${DB_HOST}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__DB_PORT__@${DB_PORT}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__DB_NAME__@${DB_NAME}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__DB_USER__@${DB_USER}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__DB_PASSWORD__@${DB_PASSWORD}@g" project_50/project_50/configs/kuber_config.py

    - sed -i -e "s@__REDIS_URL__@${REDIS_URL}@g" project_50/project_50/configs/kuber_config.py
    - sed -i -e "s@__REDIS_PORT__@${REDIS_PORT}@g" project_50/project_50/configs/kuber_config.py

    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${REPOSITORY_IMAGE} .
    - docker push ${REPOSITORY_IMAGE}

NGINX_Image_Package:
  tags:
    - kuber
  stage: package
  only:
    - master
  image: docker:18.09.6-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -f Dockerfile.nginx -t ${REPOSITORY_IMAGE_NGINX} .
    - docker push ${REPOSITORY_IMAGE_NGINX}


PROJECT_Deploy:
  tags:
    - kuber
  stage: deploy
  only:
    - master
  image: roffe/kubectl:v1.13.2
  script:
    - kubectl config set-cluster test-cluster --server=$(kubectl describe services | grep IP | sed -E 's/IP:[[:space:]]+//' | sed -E 's/Type:[[:space:]]+//' | tr -d ClusterIP)
    - NAMESPACE_NAME=$(echo -e gitdep-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME | tr -d _)
    - kubectl create secret -n "$NAMESPACE_NAME" docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$REGISTRY_DEPLOY_LOGIN" --docker-password="$REGISTRY_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl replace -n "$NAMESPACE_NAME" --force -f -
    - CI_PROJECT_NAME=$(echo -e $CI_PROJECT_NAME | tr -d _)
    #App
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp.yml
    - sed -i -e "s@__REPOSITORY_IMAGE__@${REPOSITORY_IMAGE}@g" dp.yml
    - kubectl apply -f dp.yml
    #Nginx
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp-nginx.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp-nginx.yml
    - sed -i -e "s@__REPOSITORY_IMAGE_NGINX__@${REPOSITORY_IMAGE_NGINX}@g" dp-nginx.yml
    - kubectl apply -f dp-nginx.yml
