FROM nginx:1.19.6-alpine

LABEL maintainer="devops@onix-systems.com"

ARG NGINX_COUNT_PROC

ENV NGINX_COUNT_PROC=$NGINX_COUNT_PROC

RUN sed -i -e "s#worker_processes  1;#worker_processes  ${NGINX_COUNT_PROC};#g" /etc/nginx/nginx.conf

COPY ./project_50.conf /etc/nginx/conf.d/default.conf

VOLUME [ "/var/www/app/static" ]

EXPOSE 80