SECRET_KEY = "__SECRET_KEY__"
API_VERSION = "__API_VERSION__"
DEBUG = "__DEBUG__"
ALLOWED_HOSTS = "__ALLOWED_HOSTS__"
SSL = "__SSL__"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '__DB_NAME__',
        'USER': '__DB_USER__',
        'PASSWORD': '__DB_PASSWORD__',
        'HOST': '__DB_HOST__',
        'PORT': '__DB_PORT__'
    }
}
REDIS_HOST = "__REDIS_HOST__"
REDIS_PORT = "__REDIS_PORT__"
JWT_EXPIRATION = "__JWT_EXPIRATION__"
JWT_REFRESH_TIME = "__JWT_REFRESH_TIME__"
EMAIL_BACKEND = "__EMAIL_BACKEND__"
EMAIL_HOST = "__EMAIL_HOST__"
EMAIL_USE_TLS = "__EMAIL_USE_TLS__"
EMAIL_PORT = "__EMAIL_PORT__"
EMAIL_HOST_USER = "__EMAIL_HOST_USER__"
EMAIL_HOST_PASSWORD = "__EMAIL_HOST_PASSWORD__"
DEFAULT_FROM_EMAIL = "__DEFAULT_FROM_EMAIL__"
FCM_KEY = "__FCM_KEY__"
SOCIAL_AUTH_FACEBOOK_KEY = "__SOCIAL_AUTH_FACEBOOK_KEY__"
SOCIAL_AUTH_FACEBOOK_SECRET = "__SOCIAL_AUTH_FACEBOOK_SECRET__"
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "__SOCIAL_AUTH_GOOGLE_OAUTH2_KEY__"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "__SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET__"
SOCIAL_AUTH_APPLE_ID_CLIENT = "__SOCIAL_AUTH_APPLE_ID_CLIENT__"
SOCIAL_AUTH_APPLE_ID_TEAM = "__SOCIAL_AUTH_APPLE_ID_TEAM__"
SOCIAL_AUTH_APPLE_ID_KEY = "__SOCIAL_AUTH_APPLE_ID_KEY__"
SOCIAL_AUTH_APPLE_ID_SECRET = "__SOCIAL_AUTH_APPLE_ID_SECRET__"
