SECRET_KEY = "__SECRET_KEY__"
API_VERSION = "v1"
DEBUG = True
ALLOWED_HOSTS = ['*']
SSL = False
DATABASES = {'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': '<db_name>',
    'USER': '<db_user>',
    'PASSWORD': '<db_password>',
    'HOST': 'localhost',
    'PORT': '5432'}
}
# REDIS_HOST = "__REDIS_HOST__"
# REDIS_PORT = 6379
# JWT_EXPIRATION = "__JWT_EXPIRATION__"
# JWT_REFRESH_TIME = "__JWT_REFRESH_TIME__"
# EMAIL_BACKEND = "__EMAIL_BACKEND__"
# EMAIL_HOST = "__EMAIL_HOST__"
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "__EMAIL_HOST_USER__"
# EMAIL_HOST_PASSWORD = "__EMAIL_HOST_PASSWORD__"
# DEFAULT_FROM_EMAIL = "__DEFAULT_FROM_EMAIL__"
# FCM_KEY = "__FCM_KEY__"
# SOCIAL_AUTH_FACEBOOK_KEY = "__SOCIAL_AUTH_FACEBOOK_KEY__"
# SOCIAL_AUTH_FACEBOOK_SECRET = "__SOCIAL_AUTH_FACEBOOK_SECRET__"
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "__SOCIAL_AUTH_GOOGLE_OAUTH2_KEY__"
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "__SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET__"
# SOCIAL_AUTH_APPLE_ID_CLIENT = "__SOCIAL_AUTH_APPLE_ID_CLIENT__"
# SOCIAL_AUTH_APPLE_ID_TEAM = "__SOCIAL_AUTH_APPLE_ID_TEAM__"
# SOCIAL_AUTH_APPLE_ID_KEY = "__SOCIAL_AUTH_APPLE_ID_KEY__"
# SOCIAL_AUTH_APPLE_ID_SECRET = "__SOCIAL_AUTH_APPLE_ID_SECRET__"
